name: CI
on:
  schedule: [{cron: '0 0 * * *'}]
  push: {branches: master}
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: omelkonian/setup-agda@v0
        with:
          agda-version: 2.6.2.1
          stdlib-version: 1.7
          libraries: |
            omelkonian/formal-prelude#b1f6
            omelkonian/formal-bitcoin#5803
            omelkonian/formal-bitml#6e9d
          main: Main
          token: ${{ secrets.GITHUB_TOKEN }}
