name: CI
on:
  schedule: [{cron: '0 0 * * *'}]
  push: {branches: master}
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: omelkonian/setup-agda@master
        with:
          agda-version: 2.6.3
          stdlib-version: 1.7.2
          libraries: |
            omelkonian/formal-prelude#d32c6d7
            omelkonian/formal-bitcoin#80bf272
            omelkonian/formal-bitml#737bf39
          main: Main
          token: ${{ secrets.GITHUB_TOKEN }}
          rts: -K256M -H1G -M8G -A128M
          measure-typechecking: true
          ribbon: true
