name: CI
on:
  # schedule: [{cron: '0 0 * * *'}]
  push: {branches: master}
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: omelkonian/setup-agda@v0.1
        with:
          agda-version: 2.6.2.1
          stdlib-version: 1.7
          libraries: |
            omelkonian/formal-prelude#f4f5
            omelkonian/formal-bitcoin#ae86
            omelkonian/formal-bitml#1262
          main: Main
          token: ${{ secrets.GITHUB_TOKEN }}
          rts: -K256M -H1G -M8G -A128M
